
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wow
 */
public class NewJFrame extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ResultSet rset = null;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
       prod(); // product load
        comcus(); // customer load
         con = Dbconnect.connection();
        
    }
   
    public  void  totcount(){
    
    int numberOfRaw = jTable1.getRowCount();
                double total = 0;
                for (int i = 0; i < numberOfRaw; i++) {               
                   //if checkbox is checked                    
                        double value = Double.valueOf(jTable1.getValueAt(i, 7).toString());
                        total += value;                    
                }
                tot_lbl.setText(Double.toString(total));
    
    
    
    
    }
     public void tbload() {
         String nn = inid.getText();
        try {
            String sql = "SELECT inid,cid,cname,pid,pname,pqty,unit_price,total_price,pay FROM invoice_plist where inid ='"+nn+"'";
           
            // String sql = " SELECT inid,cname, invoice_plist where name ='"+nn+"' ";
          
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
        }
         totcount();
    }
    
    
public void cal(){
     String i = p_qty.getText();
    
    if ("".equals(i)) {
         to_price.setText("");
    } else {
        Double result = Double.valueOf(p_qty.getText()) * Double.valueOf(u_price.getText());
    
    to_price.setText((String.valueOf(result)));
    }
    
     
}
public void  comcus(){ //CUSTOMER
    try {
        Statement s = Dbconnect.connection().createStatement();
                  ResultSet rs = s.executeQuery("SELECT * FROM customer");
                  Vector vv = new Vector();
                  
                  while (rs.next()) {                      
                      vv.add(rs.getString("name"));
                      DefaultComboBoxModel cmm = new DefaultComboBoxModel(vv);
                      select_cus.setModel(cmm);
                      }
              } catch (Exception e) {
              }


}
public void  prod(){ // PRODUCT
    
        try { //  Statement s = db.mys().createStatement();            
            Statement s = Dbconnect.connection().createStatement();            
          ResultSet rset = s.executeQuery("SELECT * from product");
            Vector vec = new Vector();           
          while (rset.next()){
              vec.add(rset.getString("name"));
              DefaultComboBoxModel cm = new DefaultComboBoxModel(vec);
            select_pro.setModel(cm);
             }
        } catch (SQLException e) {
        }
        }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p_qty = new javax.swing.JTextField();
        pay_m = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        select_cus = new javax.swing.JComboBox();
        city_name = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        to_price = new javax.swing.JLabel();
        u_price = new javax.swing.JLabel();
        select_pro = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tot_lbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        inid_search = new javax.swing.JTextField();
        cid_l = new javax.swing.JLabel();
        qtylb1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Invoice No:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        inid.setBackground(new java.awt.Color(204, 255, 51));
        inid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inid.setText("012");
        getContentPane().add(inid, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 16, 76, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Date :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 52, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("2018-12-16");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 48, 115, 30));

        p_qty.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        p_qty.setText("5");
        p_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_qtyActionPerformed(evt);
            }
        });
        p_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p_qtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p_qtyKeyReleased(evt);
            }
        });
        getContentPane().add(p_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 128, 30));

        pay_m.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Pament Methad", "-------------", "CASH", "CREDIT", "CHEQS" }));
        getContentPane().add(pay_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 947, 257));

        jButton1.setText("Add to cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, -1, 30));

        select_cus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ab" }));
        select_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_cusActionPerformed(evt);
            }
        });
        getContentPane().add(select_cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 59, 144, 30));

        city_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        city_name.setText("116");
        getContentPane().add(city_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 210, -1));

        p_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p_id.setText("PID");
        getContentPane().add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 45, 30));

        to_price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        to_price.setText("300.00");
        getContentPane().add(to_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 150, 30));

        u_price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        u_price.setText("250.00");
        getContentPane().add(u_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 160, 30));

        select_pro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Product", "Add Product", " " }));
        select_pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                select_proMouseClicked(evt);
            }
        });
        select_pro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                select_proMouseMoved(evt);
            }
        });
        select_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_proActionPerformed(evt);
            }
        });
        getContentPane().add(select_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 177, 38));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cashier :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Baby");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Total :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, 30));

        tot_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tot_lbl.setToolTipText("");
        getContentPane().add(tot_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 240, 30));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, -1, 30));

        inid_search.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        inid_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inid_searchActionPerformed(evt);
            }
        });
        inid_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inid_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inid_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inid_searchKeyTyped(evt);
            }
        });
        getContentPane().add(inid_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 128, 30));

        cid_l.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cid_l.setText("116");
        getContentPane().add(cid_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        qtylb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtylb1.setText("QTY");
        getContentPane().add(qtylb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 45, 30));

        jButton3.setText("<>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 50, 30));

        jButton4.setText("New Invoice");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 110, 30));

        jLabel2.setText("This is  No dispaly");
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 160, -1));

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String invid = inid.getText();
        String cusname = select_cus.getSelectedItem().toString();
        String cid = cid_l.getText();
        String pr_name = select_pro.getSelectedItem().toString();
        String pr_id = p_id.getText();
        String pqty =  p_qty.getText();
        Double tot = Double.valueOf(to_price.getText());
        Double uprice = Double.valueOf(u_price.getText());
        String payMe= pay_m.getSelectedItem().toString();
       
        try {
        String s = ("INSERT into invoice_plist (inid,cid,cname,pid,pname,pqty,unit_price,total_price,pay) VALUES ('"+invid+"','"+cid+"','"+cusname+"','"+pr_id+"','"+pr_name+"','"+pqty+"','"+uprice+"','"+tot+"','"+payMe+"')");
         
           // String s =("INSERT into invoice_plist  VALUES ('"+invid+"','"+cusname+"','"+tot+"')");
            pst = con.prepareStatement(s);
            pst.execute();
            JOptionPane.showMessageDialog(cid_l, "Added was sucsesfull");
            
            select_pro.setSelectedItem("Select Product");
            p_id.setText("");
            p_qty.setText("");
            u_price.setText("");
            to_price.setText("");
           select_pro.requestFocus();
            inid_search.setText("");
            
        } catch (SQLException e) {
        }
        tbload();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
      
                  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void select_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_proActionPerformed
         
        String grade = select_pro.getSelectedItem().toString();
        try {
              if ("Add Product".equals(grade)) {
        Product pr = new Product();
        pr.setVisible(true);
        
    } else {
          
//        Statement s =Dbconnect.connection().createStatement();
//        ResultSet rs = s.executeQuery("SELECT * FROM martinfo WHERE id='"+select_pro.getSelectedItem().toString()+"'");
//        if(rs.next()){
//        t_name.setText(rs.getString("name"));
        p_qty.requestFocus();
        p_qty.selectAll();
        Statement s = Dbconnect.connection().createStatement();
        ResultSet rss = s.executeQuery("SELECT * FROM product WHERE name='"+select_pro.getSelectedItem().toString()+"'");
                  if (rss.next()) {
                      p_id.setText(rss.getString("id"));
                      u_price.setText(rss.getString("price"));
                       } } 
        
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_select_proActionPerformed

    private void p_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_qtyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_qtyKeyPressed

    private void p_qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_qtyKeyReleased
        cal();
        
    }//GEN-LAST:event_p_qtyKeyReleased

    private void p_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_qtyActionPerformed
        
       
        
        
        
    }//GEN-LAST:event_p_qtyActionPerformed

    private void inid_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inid_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inid_searchActionPerformed

    private void inid_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inid_searchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inid_searchKeyPressed

    private void inid_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inid_searchKeyReleased
        
        String nn = inid_search.getText();
        try {
            String sql = "SELECT inid,cid,cname,pid,pname,pqty,unit_price,total_price,pay FROM invoice_plist where inid ='"+nn+"'";
           
            // String sql = " SELECT inid,cname, invoice_plist where name ='"+nn+"' ";
          
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
        }
         totcount();
          
    }//GEN-LAST:event_inid_searchKeyReleased

    private void select_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_cusActionPerformed
        String grade = select_cus.getSelectedItem().toString();
        try {
            
              if ("Add Customer".equals(grade)) {
        customer cr = new customer();
        cr.setVisible(true);
    } else {
          p_qty.requestFocus();
        Statement s = Dbconnect.connection().createStatement();
        ResultSet rss = s.executeQuery("SELECT * FROM customer WHERE name='"+select_cus.getSelectedItem().toString()+"'");
                  if (rss.next()) {
                      cid_l.setText(rss.getString("id"));
                      city_name.setText(rss.getString("city"));
                      }
              }         
        } catch (Exception e) {
        }
    }//GEN-LAST:event_select_cusActionPerformed

    private void select_proMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_select_proMouseClicked
       
    }//GEN-LAST:event_select_proMouseClicked

    private void select_proMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_select_proMouseMoved
       
    }//GEN-LAST:event_select_proMouseMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       prod();
       comcus();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int i =Integer.valueOf(inid.getText());
        i++;
        String jl = String.valueOf(i);
        inid.setText(jl);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void inid_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inid_searchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inid_searchKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         String id = inid_search.getText();

        try {
            String sql = "DELETE from invoice_plist where inid ='" + id + "'";
            pst = con.prepareStatement(sql);
            pst.execute();
            tbload();

        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cid_l;
    private javax.swing.JLabel city_name;
    private javax.swing.JLabel inid;
    private javax.swing.JTextField inid_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel p_id;
    private javax.swing.JTextField p_qty;
    private javax.swing.JComboBox pay_m;
    private javax.swing.JLabel qtylb1;
    private javax.swing.JComboBox select_cus;
    private javax.swing.JComboBox select_pro;
    private javax.swing.JLabel to_price;
    private javax.swing.JLabel tot_lbl;
    private javax.swing.JLabel u_price;
    // End of variables declaration//GEN-END:variables
}
